### ISSUE TITLE
madeHot[id] is not a function

### ISSUE THREAD

**Issue by miafmira** [loggur/babel-plugin-react-error-catcher#6] opened 2015-08-28 13:51 UTC
Trying to use this plugin but got an error:
Uncaught TypeError: madeHot[id] is not a function

**Comment by timbur** [comment] 2015-08-28 14:25
May I see your configuration?

**Comment by miafmira** [comment] 2015-08-28 14:27
Webpack:
```
var path = require('path');
var UglifyJsPlugin = require('webpack/lib/optimize/UglifyJsPlugin');
var HotModuleReplacementPlugin = require('webpack/lib/HotModuleReplacementPlugin');
var NoErrorsPlugin = require('webpack/lib/NoErrorsPlugin');
var DefinePlugin = require('webpack/lib/DefinePlugin');
var ResolverPlugin = require('webpack/lib/ResolverPlugin');
var DirectoryDescriptionFilePlugin = require('webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var entry = [
  './src/index.js'
];
var jsLoaders = [
  'babel-loader',
  'webpack-module-hot-accept'
];

var plugins = [
  new HtmlWebpackPlugin({template: 'src/index.html'}),
  new ResolverPlugin(new DirectoryDescriptionFilePlugin('bower.json', ['main'])),
  new ExtractTextPlugin('styles.css'),
  new DefinePlugin({
    __PRODUCTION__: JSON.stringify(JSON.parse(process.env.PRODUCTION || 'true'))
  })
];

if (process.env.PRODUCTION) {
  plugins.push(
    new UglifyJsPlugin({
      output: {
        comments: false
      },
      compress: {
        warnings: false,
        dead_code: true
      }
    }),
    new DefinePlugin({
      __DEV__: false
    })
  );
}

if (process.env.DEVELOPMENT) {
  entry = [
    // 'webpack-dev-server/client?http://localhost:8080',
    'webpack/hot/only-dev-server'
  ].concat(entry);

  plugins.push(new DefinePlugin({
    __DEV__: true
  }));

  // plugins.push(new HotModuleReplacementPlugin());
  plugins.push(new NoErrorsPlugin());

  // jsLoaders = ['react-hot'].concat(jsLoaders);
}

var config = {
  entry: entry,

  output: {
    path: './build',
    filename: 'bundle.js'
  },

  resolve: {
    root: [
      path.resolve(__dirname, 'bower_components'),
      path.resolve(__dirname, 'src')
    ],
    extensions: [
      "", ".js", ".jsx", ".css", ".less"
    ]
  },

  plugins: plugins,

  jscs: {
    preset: "airbnb",
    esnext: true,
    validateQuoteMarks: null,
    requireCamelCaseOrUpperCaseIdentifiers: null
  },

  module: {
    loaders: [
      {test: /\.jsx?$/, loaders: jsLoaders, exclude: [/node_modules/, /bower_components/]},
      {test: /\.css$/, loader: ExtractTextPlugin.extract('style', 'css')},
      {test: /\.less$/, loader: ExtractTextPlugin.extract('style', 'css!less')},
      {test: /\.(eot|woff|ttf|svg)/, loader: 'file?name=fonts/[name]-[hash].[ext]'},
      {test: /\.(jpe?g|png|gif)/, loader: 'file?name=images/[name]-[hash].[ext]'}
    ]
  }
};

if (process.env.DEVELOPMENT) {
  config.devtool = 'inline-source-map';
  config.devServer = {
    contentBase: './build'
  };
  config.module.preLoaders = [{
    test:    /\.jsx?$/,
    exclude: [/node_modules/, /bower_components/],
    loader: 'jscs-loader'
  }];
}

module.exports = config;
```

Babel:
```
{
  "stage": 0,
  "optional": [
    "runtime"
  ],
  "plugins": [
    "react-hot",
    "./error-catcher"
  ]
}
```

**Comment by timbur** [comment] 2015-08-28 14:33
Do you still have `react-hot-loader` installed somewhere?  I wonder if `react-hot-loader` is being loaded instead of `babel-plugin-react-hot`.  Try removing all traces of `react-hot-loader`.

**Comment by miafmira** [comment] 2015-08-28 14:38
I removed react-hot-loader from node_modules, but still have an error. Also I logged madeHot object and id and got this:
madeHot:
Object:
  /my_project_folder/src/components/layout/header/menu/dropdown.jsx$$$null: makeHot(function)
id:
  /my_project_folder/src/components/layout/header/menu/dropdown.jsx$$$HeaderMenuDropDown

as you see ids doesn't equal

**Comment by miafmira** [comment] 2015-08-28 14:45
I solved this error by removing displayName property from old components, but now I have another error:
Uncaught Error: Invariant Violation: App.getChildContext(): childContextTypes must be defined in order to use getChildContext().

**Comment by timbur** [comment] 2015-08-28 14:48
I'm not entirely sure this is an issue with `babel-plugin-react-error-catcher` or `babel-plugin-react-hot`.  Are your `childContextTypes` defined?  And have you done a full refresh?

**Comment by miafmira** [comment] 2015-08-28 15:12
Yes. I did full refresh. This is my App component:
```
import React, {PropTypes} from 'react';
import {Provider} from 'react-redux';
import store from 'store';
import {Styles} from 'material-ui';
import HTML5Backend from 'react-dnd/modules/backends/HTML5';
import { DragDropContext } from 'react-dnd';
let ThemeManager = new Styles.ThemeManager();

@DragDropContext(HTML5Backend)
export default class App {
  static childContextTypes = {
    muiTheme: PropTypes.object,
  }

  getChildContext() {
    return {
      muiTheme: ThemeManager.getCurrentTheme(),
    };
  }

  render() {
    const elements = [
      <Provider store={store} key="provider">
        {this.props.component}
      </Provider>,
    ];
    if (__DEV__) {
      const { DebugPanel, DevTools, LogMonitor } = require('redux-devtools/lib/react');
      elements.push((
        <DebugPanel top right bottom key="debug-panel">
          <DevTools store={store}
                    monitor={LogMonitor} />
        </DebugPanel>
      ));
    }

    return (
      <div>
        {elements}
      </div>
    );
  }
}
```

I tried to remove
```
static childContextTypes = {
    muiTheme: PropTypes.object,
  }

  getChildContext() {
    return {
      muiTheme: ThemeManager.getCurrentTheme(),
    };
  }
```
than I got same error from other component with getChildContext()

**Comment by timbur** [comment] 2015-08-28 16:09
Does this work without the error catcher and without hot reloading?

**Comment by miafmira** [comment] 2015-08-28 16:54
Yes, of course

**Comment by miafmira** [comment] 2015-08-28 17:03
I tried to clone this repo and add 
```
  static childContextTypes = {
    child: PropTypes.string
  }

  getChildContext() {
    return {
      child: "Test"
    }
  }
```
to babel-plugin-react-error-catcher/examples/webpack/app.jsx

After this I got same error.

**Comment by timbur** [comment] 2015-08-28 18:11
Thanks!  I think I know what the problem is now and should have it fixed shortly.

**Comment by timbur** [comment] 2015-08-28 18:32
Looks like, internally, React was checking `inst.constructor.childContextTypes` and since the `error-catcher` monkey-patches every method (including the `constructor`), said `childContextTypes` were no longer assigned to `inst.constructor`.  So I added a few lines of code that copy the statics to the constructor.  It may turn out in the future that this should be done for every method but this should fix it for you now in `v1.1.9`.  Please let me know how it goes.  :)

**Comment by miafmira** [comment] 2015-08-28 19:11
Yes! It works! Thank you very much! You are awesome. Have a great day :+1:

**Comment by timbur** [comment] 2015-08-28 19:20
Thanks, you too!

**Closed by timbur** 2015-08-28 19:20 UTC
